version: '3.4'

services:
  backgroundworker:
    image: background-worker:latest
    ports:
        - "90:1000"
    environment:
        ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
        - ~/.aws:/root/.aws:ro
    build:
      context: .
      dockerfile: BackgroundWorker/Dockerfile
